### ISSUE TITLE
Unexpected non-void return

### ISSUE THREAD

**Issue by lcossu** [rishab2113/audio_streams#2]
Hi, I've been trying to use your package to develop an app to get audio from mic and modify it.
I get this error even with the standard app with just your package's dependency added:
> Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET audio_streams OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/luca/flutter/.pub-cache/hosted/pub.dartlang.org/audio_streams-1.0.0+2/ios/Classes/SwiftAudioStreamsPlugin.swift:36:24: error: unexpected non-void return value in void function
                    return nil
                           ^~~

How can I solve this?

**Comment by rishabnayak** [comment]
Could you describe the issue you're having with some code samples - how you're initializing the library, for example

**Comment by lcossu** [comment]
I've tested two cases:
- I've created a new project supporting swift with the command provided in the instructions and then I copied "main.dart" and "pubspec.yaml" from your Example folder in the  just created project. I tried t run the app on the emulator and I get the error above.
- Then I thought there was some issue in the main, thus I created a new empty project (default counter), again with the command, and just added the dependency in pubspec.yaml. When I run the default counter project I get the error again.

This is why I think the issue is in the plugin itself.

**Comment by rishabnayak** [comment]
I tried both cases, the plugin seems to work fine for me - could you send me a link to your project, maybe I can clone the repo and see what might be going on!

**Comment by lcossu** [comment]
I have solved the issue: I had to reinstall Xcode for other reasons and now it works without any problem. 
Thank you for the support!

**Comment by rishabnayak** [comment]
Sounds good, I'm gonna go ahead and close the issue then!
